Check for malloc returning valid pointer
On some systems (even those with Glibc) the library checks of `make check'
would fail because of an undefined reference to `rpl_malloc'. This was
because we were missing an `AC_FUNC_MALLOC' in `configure.ac'.

This fixes bug #49459.